# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
default:
  interruptible: false
stages:
  - build
  - deploy

######
# build stage
# build a new container and push to harbor
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  when: on_success
  script:
    - env
    - mkdir -p /kaniko/.docker
    - "export CI_JOB_NAME_SHORT=$(echo $CI_JOB_NAME | cut -d : -f 2-)"
    - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "build; $CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/$CI_COMMIT_REF_NAME"
    - if [ -z $CI_COMMIT_TAG ]; then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:$CI_COMMIT_SHORT_SHA --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:latest;  else /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:$CI_COMMIT_TAG --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:latest; fi
  only:
    - master

deploy:
  image: harbor.containers.wurnet.nl/proxy-cache/library/alpine:3.15.0@sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3
  stage: deploy
  before_script:
    - apk add curl
  script: 
    - echo "deploy-master; $CI_COMMIT_SHORT_SHA"
    - curl -X POST -F token=${DEPLOY_TOKEN} -F "ref=master" -F "variables[VERSION_TAG]=$CI_COMMIT_SHORT_SHA" -F "variables[ENVIRONMENT]=production" -F "variables[PROJECT]=iso28258" https://git.wur.nl/api/v4/projects/7515/trigger/pipeline
  only:
    - master
  environment:
    name: production

