stages:
  - build


######
# build stage
# build a new container and push to harbor
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  when: on_success
  only:
    refs:
      - main
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/
  dependencies:
    - tag

  script:
    - "export RELEASE_VERSION=$(echo $CI_COMMIT_MESSAGE | cut -f2- -d: | tr -d ' ')"
    - echo "RELEASE_VERSION; $RELEASE_VERSION"
    - env
    - mkdir -p /kaniko/.docker
    - "export CI_JOB_NAME_SHORT=$(echo $CI_JOB_NAME | cut -d : -f 2-)"
    # export HUGO_ENV_ARG=production
    - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "build; $RELEASE_VERSION/$CI_COMMIT_SHORT_SHA/$CI_COMMIT_REF_NAME"
    - if [ -z $RELEASE_VERSION ]; then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:$CI_COMMIT_SHORT_SHA --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:latest;  else /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:$RELEASE_VERSION --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/iso28258:latest; fi


