compressionLevel: mixed

enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-dotenv.cjs
    spec: "https://unpkg.com/yarn-plugin-dotenv/bundles/@yarnpkg/plugin-dotenv.js"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
