-- IMPORTANT: This file must be idempotent, i.e. it must not fail if executed multiple times. --
-- This file is a manual migration script to add the spectral extension. --
-- Compatible with ISO 28258 v1.5, v1.8 and v1.9 schemas. --


-------------------- Core.Sensor ---------------------------
CREATE TABLE IF NOT EXISTS core.sensor
(
    model character varying NOT NULL,
    make character varying,
    uri character varying,
    sensor_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resolution real,
    zero_filling_factor integer,
    number_points integer,
    laser_wavenumber numeric,
    wavenumber_one numeric,
    wavenumber_last numeric
);

COMMENT ON TABLE core.sensor
    IS 'An instrument used to perform spectral observations on soil specimens or directly in a soil pit. An instrument can carry more than one sensor, each operating in different bands of the spectrum. The table observation_sensor provides the association between instrument and spectrum bands. The term sensor is retained for alignment with SOSA/SSN.';

COMMENT ON COLUMN core.sensor.model
    IS 'Model of this spectral instrument.';

COMMENT ON COLUMN core.sensor.make
    IS 'Make or brand of this spectral instrument.';

COMMENT ON COLUMN core.sensor.uri
    IS 'URI to an external description of the spectral instrument.';

COMMENT ON COLUMN core.sensor.sensor_id
    IS 'Synthetic primary key.';

COMMENT ON COLUMN core.sensor.resolution
    IS 'Spectral resolution';

COMMENT ON COLUMN core.sensor.zero_filling_factor
    IS 'Interpolation mode (fourier transform) to increase the digital resolution of the spectrum.';

COMMENT ON COLUMN core.sensor.number_points
    IS 'Number of wavelength intervals forming the spectrum.';

COMMENT ON COLUMN core.sensor.laser_wavenumber
    IS 'Light source or reference wavelenght.';

COMMENT ON COLUMN core.sensor.wavenumber_one
    IS 'First wavelength analysed.';

COMMENT ON COLUMN core.sensor.wavenumber_last
    IS 'Last wavelength analysed.';


-----------------------------core.procedure_spectral---------------------------------------------------


CREATE TABLE IF NOT EXISTS core.procedure_spectral
(
    label character varying NOT NULL,
    wavelenght_max numeric NOT NULL,
    wavelenght_min numeric NOT NULL,
    resolution numeric,
    uri character varying,
    procedure_spectral_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT procedure_spectral_resolution_check CHECK (resolution > 0::numeric),
    CONSTRAINT procedure_spectral_wavelenght_min_check CHECK (wavelenght_min > 0::numeric),
    CONSTRAINT procedure_spectral_check CHECK (wavelenght_max > wavelenght_min)
);

COMMENT ON TABLE core.procedure_spectral
    IS 'Identifies bands of the electro-magnetic spectrum in which a spectral sensor operates. E.g. near infra-red, ultra-violet, X-ray. The term procedure is retained for alignment with O&M and SOSA/SSN.';

COMMENT ON COLUMN core.procedure_spectral.label
    IS 'Human readabe description of the spectrum band, e.g. mid infra-red.';

COMMENT ON COLUMN core.procedure_spectral.wavelenght_max
    IS 'Upper bound of the spectrum band in nano-metres. Note that higher wavelenghts correspond to lower energy and frequency.';

COMMENT ON COLUMN core.procedure_spectral.wavelenght_min
    IS 'Lower bound of the spectrum band in nano-metres. Note that lower wavelenghts correspond to higher energy and frequency.';

COMMENT ON COLUMN core.procedure_spectral.resolution
    IS 'Interval at which the electro-magnetic signal is discretised. Expressed in nano-metres.';

COMMENT ON COLUMN core.procedure_spectral.uri
    IS 'URI to an external description of the spectral band.';

COMMENT ON COLUMN core.procedure_spectral.procedure_spectral_id
    IS 'Synthetic primary key.';


-----------------core.observation_spectral----------------------------------------------------------------------------------


CREATE TABLE IF NOT EXISTS core.observation_spectral
(
    sensor_id integer NOT NULL REFERENCES core.sensor (sensor_id),
    procedure_spectral_id integer NOT NULL REFERENCES core.procedure_spectral (procedure_spectral_id),
    unit_of_measure_id integer NOT NULL REFERENCES core.unit_of_measure (unit_of_measure_id),
    value_min numeric,
    value_max numeric,
    observation_spectral_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT observation_spectral_sensor_id_procedure_spectral_id_key UNIQUE (sensor_id, procedure_spectral_id)
);

COMMENT ON TABLE core.observation_spectral
    IS 'Matches spectral sensors (instruments) to the bands of the electro-magnetic spectrum in which they operate.';

COMMENT ON COLUMN core.observation_spectral.sensor_id
    IS 'Foreign key to the corresponding sensor (spectral instrument).';

COMMENT ON COLUMN core.observation_spectral.procedure_spectral_id
    IS 'Foreign key to the corresponding spectral procedure, identifying a band of the electro-magnetic spectrum.';

COMMENT ON COLUMN core.observation_spectral.unit_of_measure_id
    IS 'Foreign key to the corresponding unit of measure.';

COMMENT ON COLUMN core.observation_spectral.value_min
    IS 'Minimum admissable value for this combination of sensor and spectrum band.';

COMMENT ON COLUMN core.observation_spectral.value_max
    IS 'Maximum admissable value for this combination of sensor and spectrum band.';

COMMENT ON COLUMN core.observation_spectral.observation_spectral_id
    IS 'Synthetic primary key.';


-------------------- core.result_spectral_specimen ----------------------------


CREATE TABLE IF NOT EXISTS core.result_spectral_specimen
(
    observation_spectral_id integer NOT NULL REFERENCES core.observation_spectral (observation_spectral_id),
    specimen_id integer NOT NULL REFERENCES core.specimen (specimen_id),
    spectrum jsonb NOT NULL,
    individual_id integer REFERENCES metadata.individual (individual_id),
    result_spectral_specimen_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scan_date timestamp with time zone
);


COMMENT ON TABLE core.result_spectral_specimen
    IS 'Stores the discrete spectrum resulting from a spectral observation on a specific profile element.';

COMMENT ON COLUMN core.result_spectral_specimen.observation_spectral_id
    IS 'Foreign key to the corresponding spectral observation, identifying a sensor and the spectrum band in which it operates.';

COMMENT ON COLUMN core.result_spectral_specimen.specimen_id
    IS 'Foreign key to the soil specimen on which the spectral observation was performed.';

COMMENT ON COLUMN core.result_spectral_specimen.spectrum
    IS 'A vector of values resulting from the application of the spectral observation on the profile element.';

COMMENT ON COLUMN core.result_spectral_specimen.individual_id
    IS 'Foreign key to the individual responsible for the result.';

COMMENT ON COLUMN core.result_spectral_specimen.result_spectral_specimen_id
    IS 'Synthetic primary key.';

COMMENT ON COLUMN core.result_spectral_specimen.scan_date
    IS 'Scan date of the spectrum.';


-------core.calibration_set------------------------------------------------------------------------------------


CREATE TABLE IF NOT EXISTS core.calibration_set
(
    calibration_set_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL UNIQUE
);

COMMENT ON TABLE core.calibration_set
    IS 'A collection of physio-chemical results used to calibrate a spectral model.';

COMMENT ON COLUMN core.calibration_set.calibration_set_id
    IS 'Synthetic primary key.';

COMMENT ON COLUMN core.calibration_set.name
    IS 'Name, code or label identifying the calibration set.';


----------core.calibration_set_result_specimen------------------------------------------------------------------


CREATE TABLE IF NOT EXISTS core.calibration_set_result_specimen
(
    calibration_set_id integer NOT NULL REFERENCES core.calibration_set (calibration_set_id),
    result_phys_chem_specimen_id integer NOT NULL REFERENCES core.result_phys_chem_specimen (result_phys_chem_specimen_id)
);

COMMENT ON TABLE core.calibration_set_result_specimen
    IS 'Many-to-many relation enumerating the physio-chemical results composing a calibration set.';

COMMENT ON COLUMN core.calibration_set_result_specimen.calibration_set_id
    IS 'Foreign key to the calibration set, part of the primary key.';

COMMENT ON COLUMN core.calibration_set_result_specimen.result_phys_chem_specimen_id
    IS 'Foreign key to the physio-chemical results.';


-----------------------------core.model_spectral------------------------------------------------------------------


CREATE TABLE IF NOT EXISTS core.model_spectral
(
    uri character varying UNIQUE,
    name text,
    model_spectral_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    individual_id integer REFERENCES metadata.individual (individual_id),
    calibration_set_id integer REFERENCES core.calibration_set (calibration_set_id),
    organisation_id integer REFERENCES metadata.organisation (organisation_id),
    CONSTRAINT check_uri_or_name_not_null CHECK (uri IS NOT NULL OR name IS NOT NULL)
);


COMMENT ON TABLE core.model_spectral
    IS 'A computer programme able to estimate physio-chemical observation result(s) from a spectral observation result (spectrum).';

COMMENT ON COLUMN core.model_spectral.uri
    IS 'Identifies a specific version of a programme, e.g. the URI to a tag in a code forge.';

COMMENT ON COLUMN core.model_spectral.name
    IS 'Short name for the model, e.g. "My model v1.7". Can be redundant with URI.';

COMMENT ON COLUMN core.model_spectral.model_spectral_id
    IS 'Synthetic primary key.';

COMMENT ON COLUMN core.model_spectral.individual_id
    IS 'Foreign key identifying the person responsible for the model.';

COMMENT ON COLUMN core.model_spectral.calibration_set_id
    IS 'Foreign key to the calibration set on which the model was trained.';

COMMENT ON COLUMN core.model_spectral.organisation_id
    IS 'Foreign key to the organisation responsible for the model.';


-----------------------------core.observation_spectral_derived_specimen---------------------------------------------------


CREATE TABLE IF NOT EXISTS core.observation_spectral_derived_specimen
(
    model_spectral_id integer NOT NULL REFERENCES core.model_spectral (model_spectral_id),
    observation_spectral_derived_specimen_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    observation_phys_chem_specimen_id integer NOT NULL REFERENCES core.observation_phys_chem_specimen (observation_phys_chem_specimen_id),
    CONSTRAINT unique_model_observation UNIQUE (model_spectral_id, observation_phys_chem_specimen_id)
);

COMMENT ON TABLE core.observation_spectral_derived_specimen
    IS 'Physio-chemical observation for the Specimen feature of interest. Matches a particular spectral derivation model to a target physio-chemical observation.';

COMMENT ON COLUMN core.observation_spectral_derived_specimen.model_spectral_id
    IS 'Foreign key to the spectral derivation model able to estimate results for the taget physio-chemical observation from a spectral result (spectrum).';

COMMENT ON COLUMN core.observation_spectral_derived_specimen.observation_spectral_derived_specimen_id
    IS 'Synthetic primary key.';

COMMENT ON COLUMN core.observation_spectral_derived_specimen.observation_phys_chem_specimen_id
    IS 'Foreign key to the corresponding physio-chemical observation. Identified the target property, procedure and unit of measure.';


-----------------------------core.result_spectral_derived_specimen---------------------------------------------------


CREATE TABLE IF NOT EXISTS core.result_spectral_derived_specimen
(
    observation_spectral_derived_specimen_id integer NOT NULL REFERENCES core.observation_spectral_derived_specimen (observation_spectral_derived_specimen_id),
    value numeric NOT NULL,
    result_spectral_derived_specimen_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    result_spectral_specimen_id integer REFERENCES core.result_spectral_specimen (result_spectral_specimen_id),
    specimen_id integer NOT NULL REFERENCES core.specimen (specimen_id),
    organisation_id integer REFERENCES metadata.organisation (organisation_id)
);


COMMENT ON TABLE core.result_spectral_derived_specimen
    IS 'Physio-chemical result for the Specimen feature of interest derived from a spectral observation result.';

COMMENT ON COLUMN core.result_spectral_derived_specimen.observation_spectral_derived_specimen_id
    IS 'Foreign key to the derived observation, identifying the deriving model and the target physio-chemical observation.';

COMMENT ON COLUMN core.result_spectral_derived_specimen.value
    IS 'Numerical value resulting from the application of the derivation model to the refered spectral observation result.';

COMMENT ON COLUMN core.result_spectral_derived_specimen.result_spectral_derived_specimen_id
    IS 'Synthetic primary key.';

COMMENT ON COLUMN core.result_spectral_derived_specimen.result_spectral_specimen_id
    IS 'Foreign key to the spectrum result, identifying the value is derived from the spectrum result.';

COMMENT ON COLUMN core.result_spectral_derived_specimen.specimen_id
    IS 'Foreign key to the corresponding specimen.';

COMMENT ON COLUMN core.result_spectral_derived_specimen.organisation_id
    IS 'Foreign key to the organisation responsible for the result.';


-------------Trigger: trg_check_result_value_derived, Trigger function: core.check_value_result_spectral_derived_specimen()---------------------------


DROP TRIGGER IF EXISTS trg_check_result_value_derived ON core.result_spectral_derived_specimen;

DROP FUNCTION IF EXISTS core.check_result_value_derived();

CREATE OR REPLACE FUNCTION core.check_value_result_spectral_derived_specimen()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
DECLARE
    observation core.observation_phys_chem_specimen%ROWTYPE;
    spectral_specimen_specimen_id INTEGER;
BEGIN
    ---- First check for the value bounds ----
    -- Retrieve the physio-chemical observation record
    SELECT *
      INTO observation
      FROM core.observation_phys_chem_specimen p,
           core.observation_spectral_derived_specimen d
     WHERE p.observation_phys_chem_specimen_id = d.observation_phys_chem_specimen_id
       AND d.observation_spectral_derived_specimen_id = NEW.observation_spectral_derived_specimen_id;
    -- Check if the result value is within the admissable bounds
    IF NEW.value < observation.value_min OR NEW.value > observation.value_max THEN
        RAISE EXCEPTION 'Result value outside admissable bounds for the related physio-chemical observation.';
    END IF;
    ----- Second check for the specimen_id match ----
    -- Only perform the check if result_spectral_specimen_id is provided (not NULL)
    IF NEW.result_spectral_specimen_id IS NOT NULL THEN
        -- Retrieve the specimen_id from the result_spectral_specimen table
        SELECT specimen_id
        INTO spectral_specimen_specimen_id
        FROM core.result_spectral_specimen
        WHERE result_spectral_specimen_id = NEW.result_spectral_specimen_id;

        -- If no matching record is found or the specimen_id does not match, raise an error
        IF spectral_specimen_specimen_id IS NULL THEN
            RAISE EXCEPTION 'No matching result_spectral_specimen_id found in core.result_spectral_specimen';
        ELSIF spectral_specimen_specimen_id <> NEW.specimen_id THEN
            RAISE EXCEPTION 'Specimen ID mismatch: % (expected) vs. % (provided)',
                spectral_specimen_specimen_id, NEW.specimen_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$BODY$;

COMMENT ON FUNCTION core.check_value_result_spectral_derived_specimen
    IS 'Check if the new inserting derived result value is within the bounds and if the specimen id of the new inserting derived result and the related spectrum result match.';

CREATE OR REPLACE TRIGGER trg_check_value_result_spectral_derived_specimen
    BEFORE INSERT OR UPDATE
    ON core.result_spectral_derived_specimen
    FOR EACH ROW
    EXECUTE FUNCTION core.check_value_result_spectral_derived_specimen();

COMMENT ON TRIGGER trg_check_value_result_spectral_derived_specimen ON core.result_spectral_derived_specimen
    IS 'Verifies if the value assigned to the result is valid. See the function core.check_value_result_spectral_derived_specimen() function for implementation.';


-----------------------------ON DELETE CASCADE for spectral tables---------------------------------------------------
-- This section ensures that when a specimen is deleted, related spectral data is also deleted.
-- Uses dynamic constraint replacement to handle both fresh installs and updates to existing tables.

-- result_spectral_specimen.specimen_id -> specimen (CASCADE)
-- Note: Spectral extension uses inline REFERENCES, need to find auto-generated constraint name
DO $$
DECLARE
    constraint_name text;
BEGIN
    -- Find and drop any existing FK constraint on specimen_id (could be auto-named or fk_specimen)
    SELECT conname INTO constraint_name
    FROM pg_constraint
    WHERE conrelid = 'core.result_spectral_specimen'::regclass
      AND contype = 'f'
      AND EXISTS (
          SELECT 1 FROM unnest(conkey) AS k
          JOIN pg_attribute a ON a.attrelid = conrelid AND a.attnum = k
          WHERE a.attname = 'specimen_id'
      );

    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE core.result_spectral_specimen DROP CONSTRAINT %I', constraint_name);
    END IF;

    -- Add the constraint with CASCADE
    ALTER TABLE core.result_spectral_specimen
        ADD CONSTRAINT fk_specimen FOREIGN KEY (specimen_id) REFERENCES core.specimen(specimen_id) ON DELETE CASCADE;
END $$;

-- result_spectral_derived_specimen.specimen_id -> specimen (CASCADE)
DO $$
DECLARE
    constraint_name text;
BEGIN
    -- Find and drop any existing FK constraint on specimen_id
    SELECT conname INTO constraint_name
    FROM pg_constraint
    WHERE conrelid = 'core.result_spectral_derived_specimen'::regclass
      AND contype = 'f'
      AND EXISTS (
          SELECT 1 FROM unnest(conkey) AS k
          JOIN pg_attribute a ON a.attrelid = conrelid AND a.attnum = k
          WHERE a.attname = 'specimen_id'
      );

    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE core.result_spectral_derived_specimen DROP CONSTRAINT %I', constraint_name);
    END IF;

    -- Add the constraint with CASCADE
    ALTER TABLE core.result_spectral_derived_specimen
        ADD CONSTRAINT fk_specimen FOREIGN KEY (specimen_id) REFERENCES core.specimen(specimen_id) ON DELETE CASCADE;
END $$;


-----------------------------ETL FUNCTION: core.etl_insert_result_spectral_specimen---------------------------------------------------


DROP FUNCTION IF EXISTS core.etl_insert_result_spectral_specimen(integer, integer, text, integer, text);

CREATE OR REPLACE FUNCTION core.etl_insert_result_spectral_specimen(
	observation_spectral_id integer,
	specimen_id integer,
	scan_date text,
	individual_id integer,
	spectrum text)
    RETURNS core.result_spectral_specimen
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL SAFE
AS $BODY$
    INSERT INTO core.result_spectral_specimen (observation_spectral_id, specimen_id, scan_date, individual_id, spectrum)
    VALUES (
              etl_insert_result_spectral_specimen.observation_spectral_id,
              etl_insert_result_spectral_specimen.specimen_id,
              TO_TIMESTAMP(etl_insert_result_spectral_specimen.scan_date, 'DD/MM/YYYY'),
              etl_insert_result_spectral_specimen.individual_id,
              to_jsonb(spectrum::json)
              )
       ON CONFLICT DO NOTHING
       RETURNING *;
$BODY$;


-----------------------------ETL FUNCTION: core.etl_insert_result_spectral_derived_specimen---------------------------------------------------


DROP FUNCTION IF EXISTS core.etl_insert_result_spectral_derived_specimen(integer, integer, integer, integer, numeric);

CREATE OR REPLACE FUNCTION core.etl_insert_result_spectral_derived_specimen(
	observation_spectral_derived_specimen_id integer,
	specimen_id integer,
	organisation_id integer,
    result_spectral_specimen_id integer,
	value numeric)
    RETURNS core.result_spectral_derived_specimen
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL SAFE
AS $BODY$
    INSERT INTO core.result_spectral_derived_specimen (observation_spectral_derived_specimen_id, specimen_id,organisation_id,result_spectral_specimen_id, value)
    VALUES (
              etl_insert_result_spectral_derived_specimen.observation_spectral_derived_specimen_id,
              etl_insert_result_spectral_derived_specimen.specimen_id,
              etl_insert_result_spectral_derived_specimen.organisation_id,
              etl_insert_result_spectral_derived_specimen.result_spectral_specimen_id,
              etl_insert_result_spectral_derived_specimen.value
            )
       ON CONFLICT DO NOTHING
       RETURNING *;
$BODY$;

COMMENT ON FUNCTION core.etl_insert_result_spectral_derived_specimen(integer, integer, integer, integer, numeric)
    IS 'Inserts a new result spectral derived specimen into the core.result_spectral_derived_specimen table. If the result already exists, it returns the existing record.';


-----------------------------ETL FUNCTION: core.etl_bulk_insert_spectral_derived_specimen_results---------------------------------------------------
-- Bulk insert spectral derived results for specimens
-- Used by the bulk ETL process for high-performance batch inserts

DROP FUNCTION IF EXISTS core.etl_bulk_insert_spectral_derived_specimen_results(jsonb);
CREATE OR REPLACE FUNCTION core.etl_bulk_insert_spectral_derived_specimen_results(p_data jsonb)
RETURNS TABLE(inserted_count integer, skipped_count integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_inserted INT := 0;
    v_total INT := 0;
BEGIN
    -- Insert results with observation lookup, filtering out-of-bounds values
    WITH input_data AS (
        SELECT
            (r->>'specimen_id')::INT AS spec_id,
            (r->>'property_uri')::TEXT AS prop_uri,
            (r->>'procedure_uri')::TEXT AS proc_uri,
            (r->>'unit_uri')::TEXT AS u_uri,
            (r->>'model')::TEXT AS model_name,
            (r->>'organisation_name')::TEXT AS org_name,
            (r->>'value')::NUMERIC AS val
        FROM jsonb_array_elements(p_data) AS r
    ),
    input_with_observation AS (
        SELECT
            d.spec_id,
            d.val,
            osd.observation_spectral_derived_specimen_id AS obs_id,
            opc.value_min,
            opc.value_max,
            org.organisation_id AS org_id
        FROM input_data d
        -- Find the observation_phys_chem_specimen based on property/procedure/unit
        JOIN core.observation_phys_chem_specimen opc ON
            opc.property_phys_chem_id = (
                SELECT property_phys_chem_id
                FROM core.property_phys_chem
                WHERE uri ILIKE '%' || d.prop_uri
                LIMIT 1
            )
            AND opc.procedure_phys_chem_id = (
                SELECT procedure_phys_chem_id
                FROM core.procedure_phys_chem
                WHERE uri ILIKE '%' || d.proc_uri
                LIMIT 1
            )
            AND opc.unit_of_measure_id = (
                SELECT unit_of_measure_id
                FROM core.unit_of_measure
                WHERE uri ILIKE '%' || d.u_uri
                LIMIT 1
            )
        -- Find the spectral model
        JOIN core.model_spectral ms ON
            ms.name ILIKE '%' || d.model_name || '%'
        -- Find the observation_spectral_derived_specimen linking model to observation
        JOIN core.observation_spectral_derived_specimen osd ON
            osd.model_spectral_id = ms.model_spectral_id
            AND osd.observation_phys_chem_specimen_id = opc.observation_phys_chem_specimen_id
        -- Get organisation_id (optional)
        LEFT JOIN metadata.organisation org ON
            org.name ILIKE '%' || d.org_name || '%'
    ),
    -- Filter to only valid values (within bounds)
    valid_data AS (
        SELECT d.*
        FROM input_with_observation d
        WHERE (d.value_min IS NULL OR d.val >= d.value_min)
          AND (d.value_max IS NULL OR d.val <= d.value_max)
    ),
    inserted AS (
        INSERT INTO core.result_spectral_derived_specimen (
            observation_spectral_derived_specimen_id,
            specimen_id,
            organisation_id,
            result_spectral_specimen_id,
            value
        )
        SELECT
            d.obs_id,
            d.spec_id,
            d.org_id,
            NULL,  -- result_spectral_specimen_id is optional
            d.val
        FROM valid_data d
        ON CONFLICT DO NOTHING
        RETURNING 1
    )
    SELECT COUNT(*)::INT INTO v_inserted FROM inserted;

    SELECT jsonb_array_length(p_data)::INT INTO v_total;

    RETURN QUERY SELECT v_inserted, (v_total - v_inserted)::INT;
END;
$$;

COMMENT ON FUNCTION core.etl_bulk_insert_spectral_derived_specimen_results(p_data jsonb)
IS 'Bulk insert spectral derived results for specimens. Input is JSONB array with specimen_id, property_uri, procedure_uri, unit_uri, model, organisation_name, value.';


-----------------------------PROJECT-SPECIFIC GRANTS---------------------------------------------------
-- Uncomment and replace <role_r>/<role_w> with your project roles.
-- All GRANT statements are consolidated here for easier maintenance.

-- Tables (read role)
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.sensor TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.procedure_spectral TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.observation_spectral TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.result_spectral_specimen TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.calibration_set TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.calibration_set_result_specimen TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.model_spectral TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.observation_spectral_derived_specimen TO <role_r>;
-- GRANT REFERENCES, TRIGGER, SELECT ON TABLE core.result_spectral_derived_specimen TO <role_r>;

-- Tables (write role)
-- GRANT ALL ON TABLE core.sensor TO <role_w>;
-- GRANT ALL ON TABLE core.procedure_spectral TO <role_w>;
-- GRANT ALL ON TABLE core.observation_spectral TO <role_w>;
-- GRANT ALL ON TABLE core.result_spectral_specimen TO <role_w>;
-- GRANT ALL ON TABLE core.calibration_set TO <role_w>;
-- GRANT ALL ON TABLE core.calibration_set_result_specimen TO <role_w>;
-- GRANT ALL ON TABLE core.model_spectral TO <role_w>;
-- GRANT ALL ON TABLE core.observation_spectral_derived_specimen TO <role_w>;
-- GRANT ALL ON TABLE core.result_spectral_derived_specimen TO <role_w>;

-- Functions (read role)
-- GRANT EXECUTE ON FUNCTION core.check_value_result_spectral_derived_specimen() TO <role_r>;
-- GRANT EXECUTE ON FUNCTION core.etl_insert_result_spectral_specimen(integer, integer, text, integer, text) TO <role_r>;
-- GRANT EXECUTE ON FUNCTION core.etl_insert_result_spectral_derived_specimen(integer, integer, integer, integer, numeric) TO <role_r>;

-- Functions (write role)
-- GRANT EXECUTE ON FUNCTION core.check_value_result_spectral_derived_specimen() TO <role_w>;
-- GRANT EXECUTE ON FUNCTION core.etl_insert_result_spectral_specimen(integer, integer, text, integer, text) TO <role_w>;
-- GRANT EXECUTE ON FUNCTION core.etl_insert_result_spectral_derived_specimen(integer, integer, integer, integer, numeric) TO <role_w>;
